### ISSUE TITLE
photo for the string article

### ISSUE THREAD

**Issue by cecilesauder** [rbind/romain#7]
![corde](https://user-images.githubusercontent.com/7116394/36971958-bb342668-206d-11e8-99bf-767a9469f8be.JPG)

![string](https://user-images.githubusercontent.com/7116394/36971975-c82890de-206d-11e8-9446-83c1c3e30dc3.jpg)

c'est toi qui voit :P

**Comment by romainfrancois** [comment]
euh non merci 😱

**Comment by romainfrancois** [comment]
si jamais tu as le temps, il s'agit "juste" de rajouter `banner: ` dans le front matter, et refaire un `serve_site()` pour construire le html depuis le Rmd.
